language: python
python:
    - '3.8'

install:
    - pip install -r requirements-dev.txt

env:
    - PYTHONPATH=/home/travis/build/oa767/CROW

script:
    - make all_tests

deploy:
    - provider: heroku
      api_key: $HEROKU_API_KEY
      app: crow249

#after_success:
#    - ./deploy.sh
#
#notifications:
#  slack: devopsnyu:vAFcJBgAP2f73SqhWgb40Gjf
